backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Beitrag" # Used in the UI
    folder: "content/posts" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Teaser Text", name: "teaser", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Bild", name: "thumbnail", widget: "image" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "content/events" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Beschreibung",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Datum von", name: "date_from", widget: "datetime" }
      - {
          label: "Datum bis",
          name: "date_to",
          widget: "datetime",
          required: false,
        }
      - { label: "Ort", name: "location", widget: "string" }
      - { label: "Karte", name: "map", widget: "map", required: false }
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Text", name: "text", widget: "text" }
      - { label: "Datum", name: "date", widget: "datetime" }
